//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVHigherSecondaryAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFee
    {
        public int StudentFeesID { get; set; }
        public Nullable<int> StudentRollID { get; set; }
        public string TotalFees { get; set; }
        public string CreatedDate { get; set; }
        public Nullable<int> DataEntryOperatorID { get; set; }
    
        public virtual DataEntryOperator DataEntryOperator { get; set; }
        public virtual StudentRoll StudentRoll { get; set; }
    }
}
